import type { Achievement } from '@/types/types';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'complete_1_task',
    name: 'Principiante',
    description: 'Completa tu primera tarea',
    icon: 'check-circle',
    category: 'tasks',
    reward: { experience: 50, coins: 25 },
    unlocked: false,
    progress: 0,
    target: 1,
  },
  {
    id: 'complete_5_tasks',
    name: 'Productivo',
    description: 'Completa 5 tareas',
    icon: 'check-circle',
    category: 'tasks',
    reward: { experience: 100, coins: 50 },
    unlocked: false,
    progress: 0,
    target: 5,
  },
  {
    id: 'complete_25_tasks',
    name: 'Máquina de productividad',
    description: 'Completa 25 tareas',
    icon: 'check-circle',
    category: 'tasks',
    reward: { experience: 250, coins: 125 },
    unlocked: false,
    progress: 0,
    target: 25,
  },
  {
    id: 'complete_100_tasks',
    name: 'Maestro de tareas',
    description: 'Completa 100 tareas',
    icon: 'check-circle',
    category: 'tasks',
    reward: { experience: 500, coins: 250 },
    unlocked: false,
    progress: 0,
    target: 100,
  },
  {
    id: 'daily_3_tasks',
    name: 'Rutina diaria',
    description: 'Completa 3 tareas diarias',
    icon: 'calendar',
    category: 'streak',
    reward: { experience: 75, coins: 40 },
    unlocked: false,
    progress: 0,
    target: 3,
  },
  {
    id: 'daily_5_tasks',
    name: 'Hábito saludable',
    description: 'Completa 5 tareas diarias',
    icon: 'calendar',
    category: 'streak',
    reward: { experience: 150, coins: 75 },
    unlocked: false,
    progress: 0,
    target: 5,
  },
  {
    id: 'daily_10_tasks',
    name: 'Constancia ejemplar',
    description: 'Completa 10 tareas diarias',
    icon: 'calendar',
    category: 'streak',
    reward: { experience: 300, coins: 150 },
    unlocked: false,
    progress: 0,
    target: 10,
  },
  {
    id: 'reach_level_5',
    name: 'Aprendiz',
    description: 'Alcanza el nivel 5',
    icon: 'trophy',
    category: 'level',
    reward: { experience: 0, coins: 250 },
    unlocked: false,
    progress: 0,
    target: 5,
  },
  {
    id: 'reach_level_10',
    name: 'Experto',
    description: 'Alcanza el nivel 10',
    icon: 'trophy',
    category: 'level',
    reward: { experience: 0, coins: 500 },
    unlocked: false,
    progress: 0,
    target: 10,
  },
  {
    id: 'reach_level_25',
    name: 'Maestro',
    description: 'Alcanza el nivel 25',
    icon: 'trophy',
    category: 'level',
    reward: { experience: 0, coins: 1000 },
    unlocked: false,
    progress: 0,
    target: 25,
  },
  {
    id: 'buy_1_item',
    name: 'Primer compra',
    description: 'Compra tu primer ítem en la tienda',
    icon: 'shopping-bag',
    category: 'shop',
    reward: { experience: 50, coins: 25 },
    unlocked: false,
    progress: 0,
    target: 1,
  },
  {
    id: 'buy_5_items',
    name: 'Coleccionista',
    description: 'Compra 5 ítems en la tienda',
    icon: 'shopping-bag',
    category: 'shop',
    reward: { experience: 150, coins: 75 },
    unlocked: false,
    progress: 0,
    target: 5,
  },
  {
    id: 'spend_500_coins',
    name: 'Gastador',
    description: 'Gasta 500 monedas en la tienda',
    icon: 'shopping-bag',
    category: 'shop',
    reward: { experience: 200, coins: 100 },
    unlocked: false,
    progress: 0,
    target: 500,
  },
  {
    id: 'spend_1000_coins',
    name: 'Gran inversor',
    description: 'Gasta 1000 monedas en la tienda',
    icon: 'shopping-bag',
    category: 'shop',
    reward: { experience: 300, coins: 150 },
    unlocked: false,
    progress: 0,
    target: 1000,
  },
];
